services:
  - type: web
    name: crlp-rugby
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
